// This file is auto-generated by @hey-api/openapi-ts

export const AwardLeaderRowSchema = {
    properties: {
        macauthu: {
            type: 'string',
            title: 'Macauthu'
        },
        tencauthu: {
            type: 'string',
            title: 'Tencauthu'
        },
        maclb: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maclb'
        },
        tenclb: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tenclb'
        },
        value: {
            type: 'integer',
            title: 'Value'
        },
        rank: {
            type: 'integer',
            title: 'Rank'
        }
    },
    type: 'object',
    required: ['macauthu', 'tencauthu', 'value', 'rank'],
    title: 'AwardLeaderRow',
    description: 'Award leader row (top scorer / top assist provider)'
} as const;

export const AwardsResponseSchema = {
    properties: {
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        top_scorers: {
            items: {
                '$ref': '#/components/schemas/AwardLeaderRow'
            },
            type: 'array',
            title: 'Top Scorers'
        },
        top_assists: {
            items: {
                '$ref': '#/components/schemas/AwardLeaderRow'
            },
            type: 'array',
            title: 'Top Assists'
        },
        generated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Generated At'
        }
    },
    type: 'object',
    required: ['muagiai', 'generated_at'],
    title: 'AwardsResponse',
    description: 'Awards response for top scorers and assisters'
} as const;

export const CauLacBoCreateSchema = {
    properties: {
        maclb: {
            type: 'string',
            title: 'Maclb'
        },
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        tenclb: {
            type: 'string',
            title: 'Tenclb'
        },
        diachitruso: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diachitruso'
        },
        donvichuquan: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Donvichuquan'
        },
        trangphucchunha: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trangphucchunha'
        },
        trangphuckhach: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trangphuckhach'
        },
        trangphucduphong: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trangphucduphong'
        },
        masanvandong: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Masanvandong'
        }
    },
    type: 'object',
    required: ['maclb', 'muagiai', 'tenclb'],
    title: 'CauLacBoCreate',
    description: 'Create club'
} as const;

export const CauLacBoPublicSchema = {
    properties: {
        maclb: {
            type: 'string',
            title: 'Maclb'
        },
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        tenclb: {
            type: 'string',
            title: 'Tenclb'
        },
        diachitruso: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diachitruso'
        },
        donvichuquan: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Donvichuquan'
        },
        trangphucchunha: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trangphucchunha'
        },
        trangphuckhach: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trangphuckhach'
        },
        trangphucduphong: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trangphucduphong'
        },
        masanvandong: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Masanvandong'
        }
    },
    type: 'object',
    required: ['maclb', 'muagiai', 'tenclb'],
    title: 'CauLacBoPublic',
    description: 'Public club data'
} as const;

export const CauLacBoUpdateSchema = {
    properties: {
        tenclb: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tenclb'
        },
        diachitruso: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diachitruso'
        },
        donvichuquan: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Donvichuquan'
        },
        trangphucchunha: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trangphucchunha'
        },
        trangphuckhach: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trangphuckhach'
        },
        trangphucduphong: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trangphucduphong'
        },
        masanvandong: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Masanvandong'
        }
    },
    type: 'object',
    title: 'CauLacBoUpdate',
    description: 'Update club (cannot change PK fields)'
} as const;

export const CauThuCreateSchema = {
    properties: {
        macauthu: {
            type: 'string',
            title: 'Macauthu'
        },
        tencauthu: {
            type: 'string',
            title: 'Tencauthu'
        },
        ngaysinh: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ngaysinh'
        },
        noisinh: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Noisinh'
        },
        quoctich: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quoctich',
            default: 'Vietnam'
        },
        quoctichkhac: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quoctichkhac'
        },
        vitrithidau: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vitrithidau'
        },
        chieucao: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chieucao'
        },
        cannang: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cannang'
        }
    },
    type: 'object',
    required: ['macauthu', 'tencauthu'],
    title: 'CauThuCreate',
    description: 'Create player'
} as const;

export const CauThuPublicSchema = {
    properties: {
        macauthu: {
            type: 'string',
            title: 'Macauthu'
        },
        tencauthu: {
            type: 'string',
            title: 'Tencauthu'
        },
        ngaysinh: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ngaysinh'
        },
        noisinh: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Noisinh'
        },
        quoctich: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quoctich'
        },
        quoctichkhac: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quoctichkhac'
        },
        vitrithidau: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vitrithidau'
        },
        chieucao: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chieucao'
        },
        cannang: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cannang'
        }
    },
    type: 'object',
    required: ['macauthu', 'tencauthu'],
    title: 'CauThuPublic',
    description: 'Public player data'
} as const;

export const CauThuUpdateSchema = {
    properties: {
        tencauthu: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tencauthu'
        },
        ngaysinh: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ngaysinh'
        },
        noisinh: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Noisinh'
        },
        quoctich: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quoctich'
        },
        quoctichkhac: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quoctichkhac'
        },
        vitrithidau: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vitrithidau'
        },
        chieucao: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chieucao'
        },
        cannang: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cannang'
        }
    },
    type: 'object',
    title: 'CauThuUpdate',
    description: 'Update player (partial update)'
} as const;

export const ChiTietDoiBongCreateSchema = {
    properties: {
        macauthu: {
            type: 'string',
            title: 'Macauthu'
        },
        maclb: {
            type: 'string',
            title: 'Maclb'
        },
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        soaothidau: {
            type: 'integer',
            maximum: 99,
            minimum: 1,
            title: 'Soaothidau',
            description: 'Shirt number (1-99, required)'
        }
    },
    type: 'object',
    required: ['macauthu', 'maclb', 'muagiai', 'soaothidau'],
    title: 'ChiTietDoiBongCreate',
    description: 'Register player to club roster'
} as const;

export const ChiTietDoiBongPublicSchema = {
    properties: {
        macauthu: {
            type: 'string',
            title: 'Macauthu'
        },
        maclb: {
            type: 'string',
            title: 'Maclb'
        },
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        soaothidau: {
            type: 'integer',
            title: 'Soaothidau'
        }
    },
    type: 'object',
    required: ['macauthu', 'maclb', 'muagiai', 'soaothidau'],
    title: 'ChiTietDoiBongPublic',
    description: 'Public roster entry'
} as const;

export const ChiTietTrongTaiCreateSchema = {
    properties: {
        matran: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Matran'
        },
        tentrongtai: {
            type: 'string',
            title: 'Tentrongtai'
        },
        vitri: {
            type: 'string',
            title: 'Vitri'
        }
    },
    type: 'object',
    required: ['tentrongtai', 'vitri'],
    title: 'ChiTietTrongTaiCreate',
    description: 'Assign referee to match'
} as const;

export const ChiTietTrongTaiPublicSchema = {
    properties: {
        matran: {
            type: 'string',
            title: 'Matran'
        },
        tentrongtai: {
            type: 'string',
            title: 'Tentrongtai'
        },
        vitri: {
            type: 'string',
            title: 'Vitri'
        }
    },
    type: 'object',
    required: ['matran', 'tentrongtai', 'vitri'],
    title: 'ChiTietTrongTaiPublic',
    description: 'Public referee data'
} as const;

export const DisciplineResponseSchema = {
    properties: {
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        leaderboard: {
            items: {
                '$ref': '#/components/schemas/DisciplineRow'
            },
            type: 'array',
            title: 'Leaderboard'
        },
        generated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Generated At'
        },
        rules: {
            type: 'string',
            title: 'Rules',
            default: 'Discipline points: Yellow card = 1, Second yellow (2 yellows in same match) = 2, Red card = 3'
        }
    },
    type: 'object',
    required: ['muagiai', 'generated_at'],
    title: 'DisciplineResponse',
    description: 'Discipline statistics response'
} as const;

export const DisciplineRowSchema = {
    properties: {
        macauthu: {
            type: 'string',
            title: 'Macauthu'
        },
        tencauthu: {
            type: 'string',
            title: 'Tencauthu'
        },
        maclb: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maclb'
        },
        tenclb: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tenclb'
        },
        matches_played: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Matches Played'
        },
        yellow_cards: {
            type: 'integer',
            title: 'Yellow Cards'
        },
        second_yellows: {
            type: 'integer',
            title: 'Second Yellows'
        },
        red_cards: {
            type: 'integer',
            title: 'Red Cards'
        },
        discipline_points: {
            type: 'integer',
            title: 'Discipline Points'
        },
        rank: {
            type: 'integer',
            title: 'Rank'
        }
    },
    type: 'object',
    required: ['macauthu', 'tencauthu', 'yellow_cards', 'second_yellows', 'red_cards', 'discipline_points', 'rank'],
    title: 'DisciplineRow',
    description: 'Discipline statistics row (cards)'
} as const;

export const DoiHinhXuatPhatCreateSchema = {
    properties: {
        matran: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Matran'
        },
        macauthu: {
            type: 'string',
            title: 'Macauthu'
        },
        vitri: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vitri'
        },
        duocxuatphat: {
            type: 'boolean',
            title: 'Duocxuatphat',
            default: true
        },
        ladoitruong: {
            type: 'boolean',
            title: 'Ladoitruong',
            default: false
        }
    },
    type: 'object',
    required: ['macauthu'],
    title: 'DoiHinhXuatPhatCreate',
    description: 'Add player to lineup'
} as const;

export const DoiHinhXuatPhatPublicSchema = {
    properties: {
        matran: {
            type: 'string',
            title: 'Matran'
        },
        macauthu: {
            type: 'string',
            title: 'Macauthu'
        },
        vitri: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vitri'
        },
        duocxuatphat: {
            type: 'boolean',
            title: 'Duocxuatphat'
        },
        ladoitruong: {
            type: 'boolean',
            title: 'Ladoitruong'
        }
    },
    type: 'object',
    required: ['matran', 'macauthu', 'duocxuatphat', 'ladoitruong'],
    title: 'DoiHinhXuatPhatPublic',
    description: 'Public lineup entry'
} as const;

export const DoiHinhXuatPhatUpdateSchema = {
    properties: {
        vitri: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vitri'
        },
        duocxuatphat: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duocxuatphat'
        },
        ladoitruong: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ladoitruong'
        }
    },
    type: 'object',
    title: 'DoiHinhXuatPhatUpdate',
    description: 'Update lineup position'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LichThiDauCreateSchema = {
    properties: {
        matran: {
            type: 'string',
            title: 'Matran'
        },
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        vong: {
            type: 'integer',
            title: 'Vong'
        },
        thoigianthidau: {
            type: 'string',
            format: 'date-time',
            title: 'Thoigianthidau'
        },
        maclbnha: {
            type: 'string',
            title: 'Maclbnha'
        },
        maclbkhach: {
            type: 'string',
            title: 'Maclbkhach'
        },
        masanvandong: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Masanvandong'
        },
        sokhangia: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sokhangia'
        },
        nhietdo: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nhietdo'
        },
        bugiohiep1: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bugiohiep1'
        },
        bugiohiep2: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bugiohiep2'
        },
        tiso: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tiso'
        }
    },
    type: 'object',
    required: ['matran', 'muagiai', 'vong', 'thoigianthidau', 'maclbnha', 'maclbkhach'],
    title: 'LichThiDauCreate',
    description: 'Create match'
} as const;

export const LichThiDauDetailSchema = {
    properties: {
        matran: {
            type: 'string',
            title: 'Matran'
        },
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        vong: {
            type: 'integer',
            title: 'Vong'
        },
        thoigianthidau: {
            type: 'string',
            format: 'date-time',
            title: 'Thoigianthidau'
        },
        maclbnha: {
            type: 'string',
            title: 'Maclbnha'
        },
        maclbkhach: {
            type: 'string',
            title: 'Maclbkhach'
        },
        masanvandong: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Masanvandong'
        },
        sokhangia: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sokhangia'
        },
        nhietdo: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nhietdo'
        },
        bugiohiep1: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bugiohiep1'
        },
        bugiohiep2: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bugiohiep2'
        },
        tiso: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tiso'
        },
        events: {
            items: {
                '$ref': '#/components/schemas/SuKienTranDauPublic'
            },
            type: 'array',
            title: 'Events'
        },
        lineup_home: {
            items: {
                '$ref': '#/components/schemas/DoiHinhXuatPhatPublic'
            },
            type: 'array',
            title: 'Lineup Home'
        },
        lineup_away: {
            items: {
                '$ref': '#/components/schemas/DoiHinhXuatPhatPublic'
            },
            type: 'array',
            title: 'Lineup Away'
        },
        referees: {
            items: {
                '$ref': '#/components/schemas/ChiTietTrongTaiPublic'
            },
            type: 'array',
            title: 'Referees'
        }
    },
    type: 'object',
    required: ['matran', 'muagiai', 'vong', 'thoigianthidau', 'maclbnha', 'maclbkhach'],
    title: 'LichThiDauDetail',
    description: 'Match with lineup, events, referees included'
} as const;

export const LichThiDauPublicSchema = {
    properties: {
        matran: {
            type: 'string',
            title: 'Matran'
        },
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        vong: {
            type: 'integer',
            title: 'Vong'
        },
        thoigianthidau: {
            type: 'string',
            format: 'date-time',
            title: 'Thoigianthidau'
        },
        maclbnha: {
            type: 'string',
            title: 'Maclbnha'
        },
        maclbkhach: {
            type: 'string',
            title: 'Maclbkhach'
        },
        masanvandong: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Masanvandong'
        },
        sokhangia: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sokhangia'
        },
        nhietdo: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nhietdo'
        },
        bugiohiep1: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bugiohiep1'
        },
        bugiohiep2: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bugiohiep2'
        },
        tiso: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tiso'
        }
    },
    type: 'object',
    required: ['matran', 'muagiai', 'vong', 'thoigianthidau', 'maclbnha', 'maclbkhach'],
    title: 'LichThiDauPublic',
    description: 'Public match data'
} as const;

export const LichThiDauUpdateSchema = {
    properties: {
        matran: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Matran'
        },
        muagiai: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Muagiai'
        },
        vong: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vong'
        },
        thoigianthidau: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thoigianthidau'
        },
        maclbnha: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maclbnha'
        },
        maclbkhach: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maclbkhach'
        },
        masanvandong: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Masanvandong'
        },
        sokhangia: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sokhangia'
        },
        nhietdo: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nhietdo'
        },
        bugiohiep1: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bugiohiep1'
        },
        bugiohiep2: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bugiohiep2'
        },
        tiso: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tiso'
        }
    },
    type: 'object',
    title: 'LichThiDauUpdate',
    description: 'Update match (partial update)'
} as const;

export const LineupPlayerDetailSchema = {
    properties: {
        macauthu: {
            type: 'string',
            title: 'Macauthu'
        },
        tencauthu: {
            type: 'string',
            title: 'Tencauthu'
        },
        vitri: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vitri'
        },
        vitrithidau: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vitrithidau'
        },
        duocxuatphat: {
            type: 'boolean',
            title: 'Duocxuatphat'
        },
        ladoitruong: {
            type: 'boolean',
            title: 'Ladoitruong'
        },
        soaothidau: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Soaothidau'
        }
    },
    type: 'object',
    required: ['macauthu', 'tencauthu', 'duocxuatphat', 'ladoitruong'],
    title: 'LineupPlayerDetail',
    description: 'Lineup entry with player details'
} as const;

export const LineupResponseSchema = {
    properties: {
        starting_xi: {
            items: {
                '$ref': '#/components/schemas/LineupPlayerDetail'
            },
            type: 'array',
            title: 'Starting Xi'
        },
        substitutes: {
            items: {
                '$ref': '#/components/schemas/LineupPlayerDetail'
            },
            type: 'array',
            title: 'Substitutes'
        },
        captain_home: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/LineupPlayerDetail'
                },
                {
                    type: 'null'
                }
            ]
        },
        captain_away: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/LineupPlayerDetail'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'LineupResponse',
    description: 'Lineup response with starting XI and substitutes'
} as const;

export const LoaiCauThuCreateSchema = {
    properties: {
        maloaicauthu: {
            type: 'string',
            title: 'Maloaicauthu'
        },
        tenloaicauthu: {
            type: 'string',
            title: 'Tenloaicauthu'
        },
        socauthutoida: {
            type: 'integer',
            title: 'Socauthutoida'
        },
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        }
    },
    type: 'object',
    required: ['maloaicauthu', 'tenloaicauthu', 'socauthutoida', 'muagiai'],
    title: 'LoaiCauThuCreate',
    description: 'Create player type regulation'
} as const;

export const LoaiCauThuPublicSchema = {
    properties: {
        maloaicauthu: {
            type: 'string',
            title: 'Maloaicauthu'
        },
        tenloaicauthu: {
            type: 'string',
            title: 'Tenloaicauthu'
        },
        socauthutoida: {
            type: 'integer',
            title: 'Socauthutoida'
        },
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        }
    },
    type: 'object',
    required: ['maloaicauthu', 'tenloaicauthu', 'socauthutoida', 'muagiai'],
    title: 'LoaiCauThuPublic',
    description: 'Public player type data'
} as const;

export const LoaiCauThuUpdateSchema = {
    properties: {
        tenloaicauthu: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tenloaicauthu'
        },
        socauthutoida: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socauthutoida'
        }
    },
    type: 'object',
    title: 'LoaiCauThuUpdate',
    description: 'Update player type regulation'
} as const;

export const LoginRequestSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'LoginRequest',
    description: 'Login request with username and password'
} as const;

export const LoginResponseSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        },
        role: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Role'
        },
        expiresIn: {
            type: 'integer',
            title: 'Expiresin'
        }
    },
    type: 'object',
    required: ['token', 'expiresIn'],
    title: 'LoginResponse',
    description: 'Response for login endpoint'
} as const;

export const MatchStatsResponseSchema = {
    properties: {
        matran: {
            type: 'string',
            title: 'Matran'
        },
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        home_team: {
            '$ref': '#/components/schemas/MatchStatsRow'
        },
        away_team: {
            '$ref': '#/components/schemas/MatchStatsRow'
        },
        available: {
            type: 'boolean',
            title: 'Available',
            default: true
        },
        message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Message'
        }
    },
    type: 'object',
    required: ['matran', 'muagiai', 'home_team', 'away_team'],
    title: 'MatchStatsResponse',
    description: 'Match statistics response'
} as const;

export const MatchStatsRowSchema = {
    properties: {
        maclb: {
            type: 'string',
            title: 'Maclb'
        },
        tenclb: {
            type: 'string',
            title: 'Tenclb'
        },
        possession: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Possession'
        },
        shots: {
            type: 'integer',
            title: 'Shots'
        },
        shots_on_target: {
            type: 'integer',
            title: 'Shots On Target'
        },
        corners: {
            type: 'integer',
            title: 'Corners'
        },
        fouls: {
            type: 'integer',
            title: 'Fouls'
        },
        yellow_cards: {
            type: 'integer',
            title: 'Yellow Cards'
        },
        red_cards: {
            type: 'integer',
            title: 'Red Cards'
        }
    },
    type: 'object',
    required: ['maclb', 'tenclb', 'shots', 'shots_on_target', 'corners', 'fouls', 'yellow_cards', 'red_cards'],
    title: 'MatchStatsRow',
    description: 'Match statistics for one team'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const MuaGiaiCreateSchema = {
    properties: {
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        ngaybatdau: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ngaybatdau'
        },
        ngayketthuc: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ngayketthuc'
        },
        soclbthamdutoida: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Soclbthamdutoida'
        },
        lephithamgia: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lephithamgia'
        },
        socauthutoithieu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socauthutoithieu'
        },
        socauthutoida: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socauthutoida'
        },
        sothumontoithieu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sothumontoithieu'
        },
        tuoicauthutoithieu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tuoicauthutoithieu'
        },
        tuoicauthutoida: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tuoicauthutoida'
        },
        succhuatoithieu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Succhuatoithieu'
        },
        yeucausvd: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Yeucausvd'
        },
        chungchihlv: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chungchihlv'
        },
        socauthudangkythidautoida: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socauthudangkythidautoida'
        },
        thoidiemghibantoida: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thoidiemghibantoida'
        },
        trangthai: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trangthai',
            default: 'Active'
        }
    },
    type: 'object',
    required: ['muagiai'],
    title: 'MuaGiaiCreate',
    description: 'Create season with regulations'
} as const;

export const MuaGiaiPublicSchema = {
    properties: {
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        ngaybatdau: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ngaybatdau'
        },
        ngayketthuc: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ngayketthuc'
        },
        soclbthamdutoida: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Soclbthamdutoida'
        },
        lephithamgia: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lephithamgia'
        },
        socauthutoithieu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socauthutoithieu'
        },
        socauthutoida: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socauthutoida'
        },
        sothumontoithieu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sothumontoithieu'
        },
        tuoicauthutoithieu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tuoicauthutoithieu'
        },
        tuoicauthutoida: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tuoicauthutoida'
        },
        succhuatoithieu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Succhuatoithieu'
        },
        yeucausvd: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Yeucausvd'
        },
        chungchihlv: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chungchihlv'
        },
        socauthudangkythidautoida: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socauthudangkythidautoida'
        },
        thoidiemghibantoida: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thoidiemghibantoida'
        },
        trangthai: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trangthai'
        }
    },
    type: 'object',
    required: ['muagiai'],
    title: 'MuaGiaiPublic',
    description: 'Public season data with all regulations'
} as const;

export const MuaGiaiUpdateSchema = {
    properties: {
        ngaybatdau: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ngaybatdau'
        },
        ngayketthuc: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ngayketthuc'
        },
        soclbthamdutoida: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Soclbthamdutoida'
        },
        lephithamgia: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lephithamgia'
        },
        socauthutoithieu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socauthutoithieu'
        },
        socauthutoida: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socauthutoida'
        },
        sothumontoithieu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sothumontoithieu'
        },
        tuoicauthutoithieu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tuoicauthutoithieu'
        },
        tuoicauthutoida: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tuoicauthutoida'
        },
        succhuatoithieu: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Succhuatoithieu'
        },
        yeucausvd: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Yeucausvd'
        },
        chungchihlv: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Chungchihlv'
        },
        socauthudangkythidautoida: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Socauthudangkythidautoida'
        },
        thoidiemghibantoida: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Thoidiemghibantoida'
        },
        trangthai: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trangthai'
        }
    },
    type: 'object',
    title: 'MuaGiaiUpdate',
    description: 'Update season regulations'
} as const;

export const PlayerStatsResponseSchema = {
    properties: {
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        total_players: {
            type: 'integer',
            title: 'Total Players'
        },
        stats: {
            items: {
                '$ref': '#/components/schemas/PlayerStatsRow'
            },
            type: 'array',
            title: 'Stats'
        }
    },
    type: 'object',
    required: ['muagiai', 'total_players', 'stats'],
    title: 'PlayerStatsResponse',
    description: 'Player statistics response'
} as const;

export const PlayerStatsRowSchema = {
    properties: {
        macauthu: {
            type: 'string',
            title: 'Macauthu'
        },
        tencauthu: {
            type: 'string',
            title: 'Tencauthu'
        },
        maclb: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Maclb'
        },
        tenclb: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tenclb'
        },
        matches_played: {
            type: 'integer',
            title: 'Matches Played'
        },
        goals: {
            type: 'integer',
            title: 'Goals'
        },
        assists: {
            type: 'integer',
            title: 'Assists'
        },
        yellow_cards: {
            type: 'integer',
            title: 'Yellow Cards'
        },
        red_cards: {
            type: 'integer',
            title: 'Red Cards'
        }
    },
    type: 'object',
    required: ['macauthu', 'tencauthu', 'matches_played', 'goals', 'assists', 'yellow_cards', 'red_cards'],
    title: 'PlayerStatsRow',
    description: 'Player statistics for a season (computed from match events)'
} as const;

export const RosterPlayerDetailSchema = {
    properties: {
        macauthu: {
            type: 'string',
            title: 'Macauthu'
        },
        tencauthu: {
            type: 'string',
            title: 'Tencauthu'
        },
        quoctich: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Quoctich'
        },
        vitrithidau: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Vitrithidau'
        },
        soaothidau: {
            type: 'integer',
            title: 'Soaothidau'
        },
        ngaysinh: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ngaysinh'
        }
    },
    type: 'object',
    required: ['macauthu', 'tencauthu', 'soaothidau'],
    title: 'RosterPlayerDetail',
    description: 'Roster entry with player details'
} as const;

export const RosterValidationResultSchema = {
    properties: {
        valid: {
            type: 'boolean',
            title: 'Valid'
        },
        violations: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Violations'
        },
        warnings: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Warnings'
        },
        stats: {
            additionalProperties: {
                anyOf: [
                    {
                        type: 'integer'
                    },
                    {
                        type: 'null'
                    }
                ]
            },
            type: 'object',
            title: 'Stats'
        }
    },
    type: 'object',
    required: ['valid'],
    title: 'RosterValidationResult',
    description: 'Result of roster validation'
} as const;

export const SanVanDongCreateSchema = {
    properties: {
        masanvandong: {
            type: 'string',
            title: 'Masanvandong'
        },
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        tensanvandong: {
            type: 'string',
            title: 'Tensanvandong'
        },
        diachisvd: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diachisvd'
        },
        succhua: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Succhua'
        },
        danhgiafifa: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Danhgiafifa'
        }
    },
    type: 'object',
    required: ['masanvandong', 'muagiai', 'tensanvandong'],
    title: 'SanVanDongCreate',
    description: 'Create stadium'
} as const;

export const SanVanDongPublicSchema = {
    properties: {
        masanvandong: {
            type: 'string',
            title: 'Masanvandong'
        },
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        tensanvandong: {
            type: 'string',
            title: 'Tensanvandong'
        },
        diachisvd: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diachisvd'
        },
        succhua: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Succhua'
        },
        danhgiafifa: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Danhgiafifa'
        }
    },
    type: 'object',
    required: ['masanvandong', 'muagiai', 'tensanvandong'],
    title: 'SanVanDongPublic',
    description: 'Public stadium data'
} as const;

export const SanVanDongUpdateSchema = {
    properties: {
        tensanvandong: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tensanvandong'
        },
        diachisvd: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Diachisvd'
        },
        succhua: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Succhua'
        },
        danhgiafifa: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Danhgiafifa'
        }
    },
    type: 'object',
    title: 'SanVanDongUpdate',
    description: 'Update stadium (cannot change PK fields)'
} as const;

export const ScheduleGenerateRequestSchema = {
    properties: {
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        ngaybatdau_lutdi: {
            type: 'string',
            format: 'date-time',
            title: 'Ngaybatdau Lutdi'
        },
        ngaybatdau_lutve: {
            type: 'string',
            format: 'date-time',
            title: 'Ngaybatdau Lutve'
        },
        interval_days: {
            type: 'integer',
            title: 'Interval Days',
            default: 7
        }
    },
    type: 'object',
    required: ['muagiai', 'ngaybatdau_lutdi', 'ngaybatdau_lutve'],
    title: 'ScheduleGenerateRequest',
    description: 'Request to generate schedule'
} as const;

export const ScheduleGenerationResultSchema = {
    properties: {
        success: {
            type: 'boolean',
            title: 'Success'
        },
        matches_created: {
            type: 'integer',
            title: 'Matches Created'
        },
        rounds_generated: {
            type: 'integer',
            title: 'Rounds Generated'
        },
        warnings: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Warnings'
        },
        errors: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Errors'
        }
    },
    type: 'object',
    required: ['success', 'matches_created', 'rounds_generated'],
    title: 'ScheduleGenerationResult',
    description: 'Result of schedule generation'
} as const;

export const ScheduleValidateRequestSchema = {
    properties: {
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        }
    },
    type: 'object',
    required: ['muagiai'],
    title: 'ScheduleValidateRequest',
    description: 'Request to validate schedule'
} as const;

export const ScheduleValidationResultSchema = {
    properties: {
        is_valid: {
            type: 'boolean',
            title: 'Is Valid'
        },
        errors: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Errors'
        },
        warnings: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Warnings'
        },
        stats: {
            additionalProperties: {
                type: 'integer'
            },
            type: 'object',
            title: 'Stats'
        }
    },
    type: 'object',
    required: ['is_valid'],
    title: 'ScheduleValidationResult',
    description: 'Result of schedule validation'
} as const;

export const SignUpRequestSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        hoten: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hoten'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'SignUpRequest',
    description: 'Sign up request'
} as const;

export const StandingsResponseSchema = {
    properties: {
        muagiai: {
            type: 'string',
            title: 'Muagiai'
        },
        last_updated: {
            type: 'string',
            format: 'date-time',
            title: 'Last Updated'
        },
        standings: {
            items: {
                '$ref': '#/components/schemas/StandingsRow'
            },
            type: 'array',
            title: 'Standings'
        }
    },
    type: 'object',
    required: ['muagiai', 'last_updated', 'standings'],
    title: 'StandingsResponse',
    description: 'Standings table for a season'
} as const;

export const StandingsRowSchema = {
    properties: {
        position: {
            type: 'integer',
            title: 'Position'
        },
        maclb: {
            type: 'string',
            title: 'Maclb'
        },
        tenclb: {
            type: 'string',
            title: 'Tenclb'
        },
        matches_played: {
            type: 'integer',
            title: 'Matches Played'
        },
        won: {
            type: 'integer',
            title: 'Won'
        },
        drawn: {
            type: 'integer',
            title: 'Drawn'
        },
        lost: {
            type: 'integer',
            title: 'Lost'
        },
        goals_for: {
            type: 'integer',
            title: 'Goals For'
        },
        goals_against: {
            type: 'integer',
            title: 'Goals Against'
        },
        goal_difference: {
            type: 'integer',
            title: 'Goal Difference'
        },
        points: {
            type: 'integer',
            title: 'Points'
        },
        form: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Form'
        }
    },
    type: 'object',
    required: ['position', 'maclb', 'tenclb', 'matches_played', 'won', 'drawn', 'lost', 'goals_for', 'goals_against', 'goal_difference', 'points'],
    title: 'StandingsRow',
    description: 'Team standings row (computed from matches)'
} as const;

export const SuKienTranDauCreateSchema = {
    properties: {
        masukien: {
            type: 'string',
            title: 'Masukien'
        },
        loaisukien: {
            type: 'string',
            title: 'Loaisukien'
        },
        phutthidau: {
            type: 'integer',
            title: 'Phutthidau'
        },
        bugio: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bugio'
        },
        motasukien: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Motasukien'
        },
        cauthulienquan: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cauthulienquan'
        },
        matran: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Matran'
        },
        maclb: {
            type: 'string',
            title: 'Maclb'
        },
        macauthu: {
            type: 'string',
            title: 'Macauthu'
        }
    },
    type: 'object',
    required: ['masukien', 'loaisukien', 'phutthidau', 'maclb', 'macauthu'],
    title: 'SuKienTranDauCreate',
    description: 'Create match event'
} as const;

export const SuKienTranDauPublicSchema = {
    properties: {
        masukien: {
            type: 'string',
            title: 'Masukien'
        },
        loaisukien: {
            type: 'string',
            title: 'Loaisukien'
        },
        phutthidau: {
            type: 'integer',
            title: 'Phutthidau'
        },
        bugio: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bugio'
        },
        motasukien: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Motasukien'
        },
        cauthulienquan: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cauthulienquan'
        },
        matran: {
            type: 'string',
            title: 'Matran'
        },
        maclb: {
            type: 'string',
            title: 'Maclb'
        },
        macauthu: {
            type: 'string',
            title: 'Macauthu'
        }
    },
    type: 'object',
    required: ['masukien', 'loaisukien', 'phutthidau', 'matran', 'maclb', 'macauthu'],
    title: 'SuKienTranDauPublic',
    description: 'Public match event data'
} as const;

export const SuKienTranDauUpdateSchema = {
    properties: {
        loaisukien: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Loaisukien'
        },
        phutthidau: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phutthidau'
        },
        bugio: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Bugio'
        },
        motasukien: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Motasukien'
        },
        cauthulienquan: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Cauthulienquan'
        }
    },
    additionalProperties: false,
    type: 'object',
    title: 'SuKienTranDauUpdate',
    description: 'Update match event - only allows updating specific fields'
} as const;

export const TaiKhoanPublicSchema = {
    properties: {
        mataikhoan: {
            type: 'integer',
            title: 'Mataikhoan'
        },
        tendangnhap: {
            type: 'string',
            title: 'Tendangnhap'
        },
        hoten: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hoten'
        },
        email: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        manhom: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Manhom'
        },
        isactive: {
            type: 'boolean',
            title: 'Isactive'
        }
    },
    type: 'object',
    required: ['mataikhoan', 'tendangnhap', 'isactive'],
    title: 'TaiKhoanPublic',
    description: 'Public user data (excludes matkhau)'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;