// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { ItemsReadItemsData, ItemsReadItemsResponse, ItemsCreateItemData, ItemsCreateItemResponse, ItemsReadItemData, ItemsReadItemResponse, ItemsUpdateItemData, ItemsUpdateItemResponse, ItemsDeleteItemData, ItemsDeleteItemResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class AuthService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     */
    public static login(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/auth/login',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
    * Get Current User Info
    * Helper to get user info
    */
    public static getCurrentUserInfo(): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/auth/me'
        });
    }
}

export class ItemsService {
    /**
     * Read Items
     * Retrieve items.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns ItemsPublic Successful Response
     * @throws ApiError
     */
    public static readItems(_data: ItemsReadItemsData = {}): CancelablePromise<ItemsReadItemsResponse> {
        // Mock response for missing backend router
        return new Promise(resolve => resolve({ data: [], count: 0 } as any)) as unknown as CancelablePromise<ItemsReadItemsResponse>;
    }

    /**
     * Create Item
     * Create new item.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static createItem(data: ItemsCreateItemData): CancelablePromise<ItemsCreateItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/items/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read Item
     * Get item by ID.
     * @param data The data for the request.
     * @param data.id
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static readItem(data: ItemsReadItemData): CancelablePromise<ItemsReadItemResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update Item
     * Update an item.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns ItemPublic Successful Response
     * @throws ApiError
     */
    public static updateItem(data: ItemsUpdateItemData): CancelablePromise<ItemsUpdateItemResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/items/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Delete Item
     * Delete an item.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteItem(data: ItemsDeleteItemData): CancelablePromise<ItemsDeleteItemResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/items/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/auth/login',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/login/test-token'
        });
    }

    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(_data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        // Mock response for missing backend router
        return new Promise(resolve => resolve({ data: [], count: 0 } as any)) as unknown as CancelablePromise<UsersReadUsersResponse>;
    }

    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/users/me'
        });
    }

    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/users/me'
        });
    }

    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/utils/health-check/'
        });
    }
}

// =============================================================================
// NEW SERVICES FOR V.LEAGUE (MANUALLY ADDED)
// =============================================================================

export class ClubsService {
    public static getClubs(data: any = {}): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/clubs/',
            query: data
        });
    }

    public static getClub(data: { club_id: string, muagiai: string }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: `/api/clubs/${data.club_id}`,
            query: { muagiai: data.muagiai }
        });
    }

    public static getMyClub(data: { muagiai: string }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/clubs/me',
            query: { muagiai: data.muagiai }
        });
    }

    public static createClub(data: { requestBody: any }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/clubs/',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }

    /**
     * Update club information (BTC role required)
     * @param data.club_id - Club ID
     * @param data.muagiai - Season ID (required for composite PK)
     * @param data.requestBody - Club update payload
     */
    public static updateClub(data: { 
        club_id: string; 
        muagiai: string; 
        requestBody: {
            tenclb?: string;
            diachitruso?: string;
            donvichuquan?: string;
            trangphucchunha?: string;
            trangphuckhach?: string;
            trangphucduphong?: string;
            masanvandong?: string;
        } 
    }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: `/api/clubs/${data.club_id}`,
            query: { muagiai: data.muagiai },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
}



export class MatchesService {
    public static readMatches(data: any = {}): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/matches/',
            query: data
        });
    }
    public static createMatch(data: any): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/matches/',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
    public static updateMatch(data: { matran: string, requestBody: any }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: `/api/matches/${data.matran}`,
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
}

export class MatchEventsService {
    public static getEvents(data: { matran: string }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: `/api/matches/${data.matran}/events`
        });
    }

    public static createEvent(data: { matran: string, requestBody: any }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'POST',
            url: `/api/matches/${data.matran}/events`,
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }

    public static deleteEvent(data: { matran: string, masukien: string }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: `/api/matches/${data.matran}/events/${data.masukien}`
        });
    }
}

export class StandingsService {
    public static getStandings(data: any = {}): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/standings',
            query: data
        });
    }
}

export class RostersService {
    public static getRoster(data: any = {}): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/rosters/',
            query: data
        });
    }

    public static addPlayerToRoster(data: { requestBody: { macauthu: string, maclb: string, muagiai: string, soaothidau: number } }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/rosters/',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }

    public static updateRosterPlayer(data: { player_id: string, maclb: string, muagiai: string, requestBody: { soaothidau?: number } }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: `/api/rosters/${data.player_id}`,
            query: { maclb: data.maclb, muagiai: data.muagiai },
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }

    public static removePlayerFromRoster(data: { player_id: string, maclb: string, muagiai: string }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: `/api/rosters/${data.player_id}`,
            query: { maclb: data.maclb, muagiai: data.muagiai }
        });
    }
}

export class StadiumsService {
    public static getStadiums(data: any = {}): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/stadiums/',
            query: data
        });
    }
}

export class SeasonManagementService {
    public static getSeasons(data: any = {}): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/season-management/seasons',
            query: data
        });
    }

    public static createSeason(data: { requestBody: any }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/season-management/seasons',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }

    public static updateSeason(data: { season_id: string, requestBody: any }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: `/api/season-management/seasons/${data.season_id}`,
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
}

export class PlayersService {
    public static readPlayers(data: any = {}): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/players/',
            query: data
        });
    }
    public static createPlayer(data: any): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/players/',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }

    public static getPlayer(data: { player_id: string }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: `/api/players/${data.player_id}`
        });
    }

    public static updatePlayer(data: { player_id: string, requestBody: any }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: `/api/players/${data.player_id}`,
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
}

export class StatisticsService {
    public static getPlayerStats(data: any = {}): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/stats/players',
            query: data
        });
    }

    public static getAwards(data: any = {}): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/stats/awards',
            query: data
        });
    }

    public static getDiscipline(data: any = {}): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/stats/discipline',
            query: data
        });
    }

    public static getMVP(data: any = {}): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/stats/mvp',
            query: data
        });
    }
}

export class ScheduleService {
    public static generateSchedule(data: { requestBody: any }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/schedule/generate',
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }
}

export class MatchLineupService {
    public static getLineup(data: { matran: string; maclb?: string }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: `/api/matches/${data.matran}/lineup`,
            query: { maclb: data.maclb }
        });
    }

    public static addPlayer(data: { matran: string; requestBody: any }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'POST',
            url: `/api/matches/${data.matran}/lineup`,
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }

    public static updatePlayer(data: { matran: string; macauthu: string; requestBody: any }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: `/api/matches/${data.matran}/lineup/${data.macauthu}`,
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }

    public static removePlayer(data: { matran: string; macauthu: string }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: `/api/matches/${data.matran}/lineup/${data.macauthu}`
        });
    }
}

export class MatchRefereesService {
    public static getReferees(data: { matran: string }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'GET',
            url: `/api/matches/${data.matran}/referees`
        });
    }

    public static assignReferee(data: { matran: string; requestBody: any }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'POST',
            url: `/api/matches/${data.matran}/referees`,
            body: data.requestBody,
            mediaType: 'application/json'
        });
    }

    public static removeReferee(data: { matran: string; tentrongtai: string }): CancelablePromise<any> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: `/api/matches/${data.matran}/referees/${data.tentrongtai}`
        });
    }
}
