// This file is auto-generated by @hey-api/openapi-ts

/**
 * Award leader row (top scorer / top assist provider)
 */
export type AwardLeaderRow = {
    macauthu: string;
    tencauthu: string;
    maclb?: (string | null);
    tenclb?: (string | null);
    value: number;
    rank: number;
};

/**
 * Awards response for top scorers and assisters
 */
export type AwardsResponse = {
    muagiai: string;
    top_scorers?: Array<AwardLeaderRow>;
    top_assists?: Array<AwardLeaderRow>;
    generated_at: string;
};

/**
 * Create club
 */
export type CauLacBoCreate = {
    maclb: string;
    muagiai: string;
    tenclb: string;
    diachitruso?: (string | null);
    donvichuquan?: (string | null);
    trangphucchunha?: (string | null);
    trangphuckhach?: (string | null);
    trangphucduphong?: (string | null);
    masanvandong?: (string | null);
};

/**
 * Public club data
 */
export type CauLacBoPublic = {
    maclb: string;
    muagiai: string;
    tenclb: string;
    diachitruso?: (string | null);
    donvichuquan?: (string | null);
    trangphucchunha?: (string | null);
    trangphuckhach?: (string | null);
    trangphucduphong?: (string | null);
    masanvandong?: (string | null);
};

/**
 * Update club (cannot change PK fields)
 */
export type CauLacBoUpdate = {
    tenclb?: (string | null);
    diachitruso?: (string | null);
    donvichuquan?: (string | null);
    trangphucchunha?: (string | null);
    trangphuckhach?: (string | null);
    trangphucduphong?: (string | null);
    masanvandong?: (string | null);
};

/**
 * Create player
 */
export type CauThuCreate = {
    macauthu: string;
    tencauthu: string;
    ngaysinh?: (string | null);
    noisinh?: (string | null);
    quoctich?: (string | null);
    quoctichkhac?: (string | null);
    vitrithidau?: (string | null);
    chieucao?: (number | null);
    cannang?: (number | null);
};

/**
 * Public player data
 */
export type CauThuPublic = {
    macauthu: string;
    tencauthu: string;
    ngaysinh?: (string | null);
    noisinh?: (string | null);
    quoctich?: (string | null);
    quoctichkhac?: (string | null);
    vitrithidau?: (string | null);
    chieucao?: (number | null);
    cannang?: (number | null);
};

/**
 * Update player (partial update)
 */
export type CauThuUpdate = {
    tencauthu?: (string | null);
    ngaysinh?: (string | null);
    noisinh?: (string | null);
    quoctich?: (string | null);
    quoctichkhac?: (string | null);
    vitrithidau?: (string | null);
    chieucao?: (number | null);
    cannang?: (number | null);
};

/**
 * Register player to club roster
 */
export type ChiTietDoiBongCreate = {
    macauthu: string;
    maclb: string;
    muagiai: string;
    /**
     * Shirt number (1-99, required)
     */
    soaothidau: number;
};

/**
 * Public roster entry
 */
export type ChiTietDoiBongPublic = {
    macauthu: string;
    maclb: string;
    muagiai: string;
    soaothidau: number;
};

/**
 * Assign referee to match
 */
export type ChiTietTrongTaiCreate = {
    matran?: (string | null);
    tentrongtai: string;
    vitri: string;
};

/**
 * Public referee data
 */
export type ChiTietTrongTaiPublic = {
    matran: string;
    tentrongtai: string;
    vitri: string;
};

/**
 * Discipline statistics response
 */
export type DisciplineResponse = {
    muagiai: string;
    leaderboard?: Array<DisciplineRow>;
    generated_at: string;
    rules?: string;
};

/**
 * Discipline statistics row (cards)
 */
export type DisciplineRow = {
    macauthu: string;
    tencauthu: string;
    maclb?: (string | null);
    tenclb?: (string | null);
    matches_played?: (number | null);
    yellow_cards: number;
    second_yellows: number;
    red_cards: number;
    discipline_points: number;
    rank: number;
};

/**
 * Add player to lineup
 */
export type DoiHinhXuatPhatCreate = {
    matran?: (string | null);
    macauthu: string;
    vitri?: (string | null);
    duocxuatphat?: boolean;
    ladoitruong?: boolean;
};

/**
 * Public lineup entry
 */
export type DoiHinhXuatPhatPublic = {
    matran: string;
    macauthu: string;
    vitri?: (string | null);
    duocxuatphat: boolean;
    ladoitruong: boolean;
};

/**
 * Update lineup position
 */
export type DoiHinhXuatPhatUpdate = {
    vitri?: (string | null);
    duocxuatphat?: (boolean | null);
    ladoitruong?: (boolean | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

/**
 * Create match
 */
export type LichThiDauCreate = {
    matran: string;
    muagiai: string;
    vong: number;
    thoigianthidau: string;
    maclbnha: string;
    maclbkhach: string;
    masanvandong?: (string | null);
    sokhangia?: (number | null);
    nhietdo?: (number | null);
    bugiohiep1?: (number | null);
    bugiohiep2?: (number | null);
    tiso?: (string | null);
};

/**
 * Match with lineup, events, referees included
 */
export type LichThiDauDetail = {
    matran: string;
    muagiai: string;
    vong: number;
    thoigianthidau: string;
    maclbnha: string;
    maclbkhach: string;
    masanvandong?: (string | null);
    sokhangia?: (number | null);
    nhietdo?: (number | null);
    bugiohiep1?: (number | null);
    bugiohiep2?: (number | null);
    tiso?: (string | null);
    events?: Array<SuKienTranDauPublic>;
    lineup_home?: Array<DoiHinhXuatPhatPublic>;
    lineup_away?: Array<DoiHinhXuatPhatPublic>;
    referees?: Array<ChiTietTrongTaiPublic>;
};

/**
 * Public match data
 */
export type LichThiDauPublic = {
    matran: string;
    muagiai: string;
    vong: number;
    thoigianthidau: string;
    maclbnha: string;
    maclbkhach: string;
    masanvandong?: (string | null);
    sokhangia?: (number | null);
    nhietdo?: (number | null);
    bugiohiep1?: (number | null);
    bugiohiep2?: (number | null);
    tiso?: (string | null);
};

/**
 * Update match (partial update)
 */
export type LichThiDauUpdate = {
    matran?: (string | null);
    muagiai?: (string | null);
    vong?: (number | null);
    thoigianthidau?: (string | null);
    maclbnha?: (string | null);
    maclbkhach?: (string | null);
    masanvandong?: (string | null);
    sokhangia?: (number | null);
    nhietdo?: (number | null);
    bugiohiep1?: (number | null);
    bugiohiep2?: (number | null);
    tiso?: (string | null);
};

/**
 * Lineup entry with player details
 */
export type LineupPlayerDetail = {
    macauthu: string;
    tencauthu: string;
    vitri?: (string | null);
    vitrithidau?: (string | null);
    duocxuatphat: boolean;
    ladoitruong: boolean;
    soaothidau?: (number | null);
};

/**
 * Lineup response with starting XI and substitutes
 */
export type LineupResponse = {
    starting_xi?: Array<LineupPlayerDetail>;
    substitutes?: Array<LineupPlayerDetail>;
    captain_home?: (LineupPlayerDetail | null);
    captain_away?: (LineupPlayerDetail | null);
};

/**
 * Create player type regulation
 */
export type LoaiCauThuCreate = {
    maloaicauthu: string;
    tenloaicauthu: string;
    socauthutoida: number;
    muagiai: string;
};

/**
 * Public player type data
 */
export type LoaiCauThuPublic = {
    maloaicauthu: string;
    tenloaicauthu: string;
    socauthutoida: number;
    muagiai: string;
};

/**
 * Update player type regulation
 */
export type LoaiCauThuUpdate = {
    tenloaicauthu?: (string | null);
    socauthutoida?: (number | null);
};

/**
 * Login request with username and password
 */
export type LoginRequest = {
    username: string;
    password: string;
};

/**
 * Response for login endpoint
 */
export type LoginResponse = {
    token: string;
    token_type?: string;
    role?: (string | null);
    expiresIn: number;
};

/**
 * Match statistics response
 */
export type MatchStatsResponse = {
    matran: string;
    muagiai: string;
    home_team: MatchStatsRow;
    away_team: MatchStatsRow;
    available?: boolean;
    message?: (string | null);
};

/**
 * Match statistics for one team
 */
export type MatchStatsRow = {
    maclb: string;
    tenclb: string;
    possession?: (number | null);
    shots: number;
    shots_on_target: number;
    corners: number;
    fouls: number;
    yellow_cards: number;
    red_cards: number;
};

export type Message = {
    message: string;
};

/**
 * Create season with regulations
 */
export type MuaGiaiCreate = {
    muagiai: string;
    ngaybatdau?: (string | null);
    ngayketthuc?: (string | null);
    soclbthamdutoida?: (number | null);
    lephithamgia?: (number | null);
    socauthutoithieu?: (number | null);
    socauthutoida?: (number | null);
    sothumontoithieu?: (number | null);
    tuoicauthutoithieu?: (number | null);
    tuoicauthutoida?: (number | null);
    succhuatoithieu?: (number | null);
    yeucausvd?: (string | null);
    chungchihlv?: (string | null);
    socauthudangkythidautoida?: (number | null);
    thoidiemghibantoida?: (number | null);
    trangthai?: (string | null);
};

/**
 * Public season data with all regulations
 */
export type MuaGiaiPublic = {
    muagiai: string;
    ngaybatdau?: (string | null);
    ngayketthuc?: (string | null);
    soclbthamdutoida?: (number | null);
    lephithamgia?: (number | null);
    socauthutoithieu?: (number | null);
    socauthutoida?: (number | null);
    sothumontoithieu?: (number | null);
    tuoicauthutoithieu?: (number | null);
    tuoicauthutoida?: (number | null);
    succhuatoithieu?: (number | null);
    yeucausvd?: (string | null);
    chungchihlv?: (string | null);
    socauthudangkythidautoida?: (number | null);
    thoidiemghibantoida?: (number | null);
    trangthai?: (string | null);
};

/**
 * Update season regulations
 */
export type MuaGiaiUpdate = {
    ngaybatdau?: (string | null);
    ngayketthuc?: (string | null);
    soclbthamdutoida?: (number | null);
    lephithamgia?: (number | null);
    socauthutoithieu?: (number | null);
    socauthutoida?: (number | null);
    sothumontoithieu?: (number | null);
    tuoicauthutoithieu?: (number | null);
    tuoicauthutoida?: (number | null);
    succhuatoithieu?: (number | null);
    yeucausvd?: (string | null);
    chungchihlv?: (string | null);
    socauthudangkythidautoida?: (number | null);
    thoidiemghibantoida?: (number | null);
    trangthai?: (string | null);
};

/**
 * Player statistics response
 */
export type PlayerStatsResponse = {
    muagiai: string;
    total_players: number;
    stats: Array<PlayerStatsRow>;
};

/**
 * Player statistics for a season (computed from match events)
 */
export type PlayerStatsRow = {
    macauthu: string;
    tencauthu: string;
    maclb?: (string | null);
    tenclb?: (string | null);
    matches_played: number;
    goals: number;
    assists: number;
    yellow_cards: number;
    red_cards: number;
};

/**
 * Roster entry with player details
 */
export type RosterPlayerDetail = {
    macauthu: string;
    tencauthu: string;
    quoctich?: (string | null);
    vitrithidau?: (string | null);
    soaothidau: number;
    ngaysinh?: (string | null);
};

/**
 * Result of roster validation
 */
export type RosterValidationResult = {
    valid: boolean;
    violations?: Array<(string)>;
    warnings?: Array<(string)>;
    stats?: {
        [key: string]: (number | null);
    };
};

/**
 * Create stadium
 */
export type SanVanDongCreate = {
    masanvandong: string;
    muagiai: string;
    tensanvandong: string;
    diachisvd?: (string | null);
    succhua?: (number | null);
    danhgiafifa?: (string | null);
};

/**
 * Public stadium data
 */
export type SanVanDongPublic = {
    masanvandong: string;
    muagiai: string;
    tensanvandong: string;
    diachisvd?: (string | null);
    succhua?: (number | null);
    danhgiafifa?: (string | null);
};

/**
 * Update stadium (cannot change PK fields)
 */
export type SanVanDongUpdate = {
    tensanvandong?: (string | null);
    diachisvd?: (string | null);
    succhua?: (number | null);
    danhgiafifa?: (string | null);
};

/**
 * Request to generate schedule
 */
export type ScheduleGenerateRequest = {
    muagiai: string;
    ngaybatdau_lutdi: string;
    ngaybatdau_lutve: string;
    interval_days?: number;
};

/**
 * Result of schedule generation
 */
export type ScheduleGenerationResult = {
    success: boolean;
    matches_created: number;
    rounds_generated: number;
    warnings?: Array<(string)>;
    errors?: Array<(string)>;
};

/**
 * Request to validate schedule
 */
export type ScheduleValidateRequest = {
    muagiai: string;
};

/**
 * Result of schedule validation
 */
export type ScheduleValidationResult = {
    is_valid: boolean;
    errors?: Array<(string)>;
    warnings?: Array<(string)>;
    stats?: {
        [key: string]: (number);
    };
};

/**
 * Sign up request
 */
export type SignUpRequest = {
    username: string;
    password: string;
    hoten?: (string | null);
    email?: (string | null);
};

/**
 * Standings table for a season
 */
export type StandingsResponse = {
    muagiai: string;
    last_updated: string;
    standings: Array<StandingsRow>;
};

/**
 * Team standings row (computed from matches)
 */
export type StandingsRow = {
    position: number;
    maclb: string;
    tenclb: string;
    matches_played: number;
    won: number;
    drawn: number;
    lost: number;
    goals_for: number;
    goals_against: number;
    goal_difference: number;
    points: number;
    form?: (string | null);
};

/**
 * Create match event
 */
export type SuKienTranDauCreate = {
    masukien: string;
    loaisukien: string;
    phutthidau: number;
    bugio?: (number | null);
    motasukien?: (string | null);
    cauthulienquan?: (string | null);
    matran?: (string | null);
    maclb: string;
    macauthu: string;
};

/**
 * Public match event data
 */
export type SuKienTranDauPublic = {
    masukien: string;
    loaisukien: string;
    phutthidau: number;
    bugio?: (number | null);
    motasukien?: (string | null);
    cauthulienquan?: (string | null);
    matran: string;
    maclb: string;
    macauthu: string;
};

/**
 * Update match event - only allows updating specific fields
 */
export type SuKienTranDauUpdate = {
    loaisukien?: (string | null);
    phutthidau?: (number | null);
    bugio?: (number | null);
    motasukien?: (string | null);
    cauthulienquan?: (string | null);
};

/**
 * Public user data (excludes matkhau)
 */
export type TaiKhoanPublic = {
    mataikhoan: number;
    tendangnhap: string;
    hoten?: (string | null);
    email?: (string | null);
    manhom?: (number | null);
    isactive: boolean;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: number;
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type AuthLoginData = {
    requestBody: LoginRequest;
};

export type AuthLoginResponse = (LoginResponse);

export type AuthSignupData = {
    requestBody: SignUpRequest;
};

export type AuthSignupResponse = (TaiKhoanPublic);

export type AuthLogoutResponse = (Message);

export type AuthGetCurrentUserInfoResponse = (TaiKhoanPublic);

export type ClubsGetClubsData = {
    limit?: number;
    /**
     * Filter by season, e.g., '2024-2025'
     */
    muagiai?: (string | null);
    skip?: number;
};

export type ClubsGetClubsResponse = (Array<CauLacBoPublic>);

export type ClubsCreateClubData = {
    requestBody: CauLacBoCreate;
};

export type ClubsCreateClubResponse = (CauLacBoPublic);

export type ClubsGetClubData = {
    clubId: string;
    /**
     * Season ID (required for composite PK)
     */
    muagiai: string;
};

export type ClubsGetClubResponse = (CauLacBoPublic);

export type ClubsUpdateClubData = {
    clubId: string;
    /**
     * Season ID (required for composite PK)
     */
    muagiai: string;
    requestBody: CauLacBoUpdate;
};

export type ClubsUpdateClubResponse = (CauLacBoPublic);

export type ClubsDeleteClubData = {
    clubId: string;
    /**
     * Season ID (required for composite PK)
     */
    muagiai: string;
};

export type ClubsDeleteClubResponse = (Message);

export type MatchesReadMatchesData = {
    denngay?: (string | null);
    limit?: number;
    maclb?: (string | null);
    muagiai?: (string | null);
    skip?: number;
    tungay?: (string | null);
    vong?: (number | null);
};

export type MatchesReadMatchesResponse = (Array<LichThiDauPublic>);

export type MatchesCreateMatchData = {
    requestBody: LichThiDauCreate;
};

export type MatchesCreateMatchResponse = (LichThiDauPublic);

export type MatchesReadMatchData = {
    matran: string;
};

export type MatchesReadMatchResponse = (LichThiDauDetail);

export type MatchesUpdateMatchData = {
    matran: string;
    requestBody: LichThiDauUpdate;
};

export type MatchesUpdateMatchResponse = (LichThiDauPublic);

export type MatchesDeleteMatchData = {
    matran: string;
};

export type MatchesDeleteMatchResponse = (Message);

export type MatchEventsReadMatchEventsData = {
    loaisukien?: (string | null);
    matran: string;
};

export type MatchEventsReadMatchEventsResponse = (Array<SuKienTranDauPublic>);

export type MatchEventsCreateMatchEventData = {
    matran: string;
    requestBody: SuKienTranDauCreate;
};

export type MatchEventsCreateMatchEventResponse = (SuKienTranDauPublic);

export type MatchEventsUpdateMatchEventData = {
    masukien: string;
    matran: string;
    requestBody: SuKienTranDauUpdate;
};

export type MatchEventsUpdateMatchEventResponse = (SuKienTranDauPublic);

export type MatchEventsDeleteMatchEventData = {
    masukien: string;
    matran: string;
};

export type MatchEventsDeleteMatchEventResponse = (Message);

export type MatchLineupReadMatchLineupData = {
    maclb?: (string | null);
    matran: string;
};

export type MatchLineupReadMatchLineupResponse = (LineupResponse);

export type MatchLineupAddPlayerToLineupData = {
    matran: string;
    requestBody: DoiHinhXuatPhatCreate;
};

export type MatchLineupAddPlayerToLineupResponse = (DoiHinhXuatPhatPublic);

export type MatchLineupUpdateLineupEntryData = {
    macauthu: string;
    matran: string;
    requestBody: DoiHinhXuatPhatUpdate;
};

export type MatchLineupUpdateLineupEntryResponse = (DoiHinhXuatPhatPublic);

export type MatchLineupRemovePlayerFromLineupData = {
    macauthu: string;
    matran: string;
};

export type MatchLineupRemovePlayerFromLineupResponse = (Message);

export type MatchRefereesReadMatchRefereesData = {
    matran: string;
};

export type MatchRefereesReadMatchRefereesResponse = (Array<ChiTietTrongTaiPublic>);

export type MatchRefereesAssignRefereeToMatchData = {
    matran: string;
    requestBody: ChiTietTrongTaiCreate;
};

export type MatchRefereesAssignRefereeToMatchResponse = (ChiTietTrongTaiPublic);

export type MatchRefereesRemoveRefereeFromMatchData = {
    matran: string;
    tentrongtai: string;
};

export type MatchRefereesRemoveRefereeFromMatchResponse = (Message);

export type PlayersGetPlayersData = {
    /**
     * Search by player name
     */
    keyword?: (string | null);
    limit?: number;
    /**
     * Filter by nationality (e.g., 'VN')
     */
    quoctich?: (string | null);
    skip?: number;
    /**
     * Filter by position (GK, DF, MF, FW)
     */
    vitrithidau?: (string | null);
};

export type PlayersGetPlayersResponse = (Array<CauThuPublic>);

export type PlayersCreatePlayerData = {
    requestBody: CauThuCreate;
};

export type PlayersCreatePlayerResponse = (CauThuPublic);

export type PlayersGetPlayerData = {
    playerId: string;
};

export type PlayersGetPlayerResponse = (CauThuPublic);

export type PlayersUpdatePlayerData = {
    playerId: string;
    requestBody: CauThuUpdate;
};

export type PlayersUpdatePlayerResponse = (CauThuPublic);

export type PlayersDeletePlayerData = {
    playerId: string;
};

export type PlayersDeletePlayerResponse = (Message);

export type RostersAddPlayerToRosterData = {
    requestBody: ChiTietDoiBongCreate;
};

export type RostersAddPlayerToRosterResponse = (ChiTietDoiBongPublic);

export type RostersGetRosterData = {
    /**
     * Club ID (required)
     */
    maclb: string;
    /**
     * Season ID (required)
     */
    muagiai: string;
};

export type RostersGetRosterResponse = (Array<RosterPlayerDetail>);

export type RostersRemovePlayerFromRosterData = {
    /**
     * Club ID (required)
     */
    maclb: string;
    /**
     * Season ID (required)
     */
    muagiai: string;
    playerId: string;
};

export type RostersRemovePlayerFromRosterResponse = (Message);

export type RostersValidateRosterData = {
    /**
     * Club ID (required)
     */
    maclb: string;
    /**
     * Season ID (required)
     */
    muagiai: string;
};

export type RostersValidateRosterResponse = (RosterValidationResult);

export type ScheduleGetScheduleData = {
    muagiai: string;
};

export type ScheduleGetScheduleResponse = (Array<LichThiDauPublic>);

export type ScheduleGenerateScheduleData = {
    requestBody: ScheduleGenerateRequest;
};

export type ScheduleGenerateScheduleResponse = (ScheduleGenerationResult);

export type ScheduleValidateScheduleData = {
    requestBody: ScheduleValidateRequest;
};

export type ScheduleValidateScheduleResponse = (ScheduleValidationResult);

export type SeasonManagementGetSeasonsData = {
    limit?: number;
    skip?: number;
};

export type SeasonManagementGetSeasonsResponse = (Array<MuaGiaiPublic>);

export type SeasonManagementCreateSeasonData = {
    requestBody: MuaGiaiCreate;
};

export type SeasonManagementCreateSeasonResponse = (MuaGiaiPublic);

export type SeasonManagementGetSeasonData = {
    seasonId: string;
};

export type SeasonManagementGetSeasonResponse = (MuaGiaiPublic);

export type SeasonManagementUpdateSeasonData = {
    requestBody: MuaGiaiUpdate;
    seasonId: string;
};

export type SeasonManagementUpdateSeasonResponse = (MuaGiaiPublic);

export type SeasonManagementDeleteSeasonData = {
    seasonId: string;
};

export type SeasonManagementDeleteSeasonResponse = (Message);

export type SeasonManagementGetPlayerTypesData = {
    limit?: number;
    /**
     * Filter by season, e.g., '2024-2025'
     */
    muagiai?: (string | null);
    skip?: number;
};

export type SeasonManagementGetPlayerTypesResponse = (Array<LoaiCauThuPublic>);

export type SeasonManagementCreatePlayerTypeData = {
    requestBody: LoaiCauThuCreate;
};

export type SeasonManagementCreatePlayerTypeResponse = (LoaiCauThuPublic);

export type SeasonManagementGetPlayerTypeData = {
    playerTypeId: string;
};

export type SeasonManagementGetPlayerTypeResponse = (LoaiCauThuPublic);

export type SeasonManagementUpdatePlayerTypeData = {
    playerTypeId: string;
    requestBody: LoaiCauThuUpdate;
};

export type SeasonManagementUpdatePlayerTypeResponse = (LoaiCauThuPublic);

export type SeasonManagementDeletePlayerTypeData = {
    playerTypeId: string;
};

export type SeasonManagementDeletePlayerTypeResponse = (Message);

export type StadiumsGetStadiumsData = {
    limit?: number;
    /**
     * Filter by season, e.g., '2024-2025'
     */
    muagiai?: (string | null);
    skip?: number;
};

export type StadiumsGetStadiumsResponse = (Array<SanVanDongPublic>);

export type StadiumsCreateStadiumData = {
    requestBody: SanVanDongCreate;
};

export type StadiumsCreateStadiumResponse = (SanVanDongPublic);

export type StadiumsGetStadiumData = {
    /**
     * Season ID (required for composite PK)
     */
    muagiai: string;
    stadiumId: string;
};

export type StadiumsGetStadiumResponse = (SanVanDongPublic);

export type StadiumsUpdateStadiumData = {
    /**
     * Season ID (required for composite PK)
     */
    muagiai: string;
    requestBody: SanVanDongUpdate;
    stadiumId: string;
};

export type StadiumsUpdateStadiumResponse = (SanVanDongPublic);

export type StadiumsDeleteStadiumData = {
    /**
     * Season ID (required for composite PK)
     */
    muagiai: string;
    stadiumId: string;
};

export type StadiumsDeleteStadiumResponse = (Message);

export type StandingsGetStandingsData = {
    /**
     * Season ID (e.g., '2024-2025')
     */
    muagiai: string;
};

export type StandingsGetStandingsResponse = (StandingsResponse);

export type StatisticsGetPlayerStatsData = {
    /**
     * Season ID (e.g., '2024-2025')
     */
    muagiai: string;
};

export type StatisticsGetPlayerStatsResponse = (PlayerStatsResponse);

export type StatisticsGetMatchStatsData = {
    matran: string;
};

export type StatisticsGetMatchStatsResponse = (MatchStatsResponse);

export type StatisticsGetAwardsData = {
    /**
     * Max number to return (ties may exceed limit)
     */
    limit?: number;
    /**
     * Season ID (e.g., '2024-2025')
     */
    muagiai: string;
};

export type StatisticsGetAwardsResponse = (AwardsResponse);

export type StatisticsGetDisciplineData = {
    /**
     * Max number to return (ties may exceed limit)
     */
    limit?: number;
    /**
     * Season ID (e.g., '2024-2025')
     */
    muagiai: string;
};

export type StatisticsGetDisciplineResponse = (DisciplineResponse);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);