"""sync_db_with_models_v2

Revision ID: aaa7cdd7f87a
Revises: e2754c7a9556
Create Date: 2025-12-20 09:41:40.471704

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'aaa7cdd7f87a'
down_revision = 'e2754c7a9556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('muagiai', 'tenmuagiai')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('muagiai', sa.Column('tenmuagiai', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
