/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutTeamsRouteImport } from './routes/_layout/teams'
import { Route as LayoutTeamManagerRouteImport } from './routes/_layout/team-manager'
import { Route as LayoutStatsRouteImport } from './routes/_layout/stats'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutLeagueTableRouteImport } from './routes/_layout/league-table'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutFixturesRouteImport } from './routes/_layout/fixtures'
import { Route as LayoutAdminDashboardRouteImport } from './routes/_layout/admin-dashboard'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamsRoute = LayoutTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutTeamManagerRoute = LayoutTeamManagerRouteImport.update({
  id: '/team-manager',
  path: '/team-manager',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutStatsRoute = LayoutStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLeagueTableRoute = LayoutLeagueTableRouteImport.update({
  id: '/league-table',
  path: '/league-table',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFixturesRoute = LayoutFixturesRouteImport.update({
  id: '/fixtures',
  path: '/fixtures',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminDashboardRoute = LayoutAdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/admin-dashboard': typeof LayoutAdminDashboardRoute
  '/fixtures': typeof LayoutFixturesRoute
  '/items': typeof LayoutItemsRoute
  '/league-table': typeof LayoutLeagueTableRoute
  '/settings': typeof LayoutSettingsRoute
  '/stats': typeof LayoutStatsRoute
  '/team-manager': typeof LayoutTeamManagerRoute
  '/teams': typeof LayoutTeamsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/admin-dashboard': typeof LayoutAdminDashboardRoute
  '/fixtures': typeof LayoutFixturesRoute
  '/items': typeof LayoutItemsRoute
  '/league-table': typeof LayoutLeagueTableRoute
  '/settings': typeof LayoutSettingsRoute
  '/stats': typeof LayoutStatsRoute
  '/team-manager': typeof LayoutTeamManagerRoute
  '/teams': typeof LayoutTeamsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/admin-dashboard': typeof LayoutAdminDashboardRoute
  '/_layout/fixtures': typeof LayoutFixturesRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/league-table': typeof LayoutLeagueTableRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/stats': typeof LayoutStatsRoute
  '/_layout/team-manager': typeof LayoutTeamManagerRoute
  '/_layout/teams': typeof LayoutTeamsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/admin-dashboard'
    | '/fixtures'
    | '/items'
    | '/league-table'
    | '/settings'
    | '/stats'
    | '/team-manager'
    | '/teams'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/admin-dashboard'
    | '/fixtures'
    | '/items'
    | '/league-table'
    | '/settings'
    | '/stats'
    | '/team-manager'
    | '/teams'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/admin-dashboard'
    | '/_layout/fixtures'
    | '/_layout/items'
    | '/_layout/league-table'
    | '/_layout/settings'
    | '/_layout/stats'
    | '/_layout/team-manager'
    | '/_layout/teams'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/teams': {
      id: '/_layout/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof LayoutTeamsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/team-manager': {
      id: '/_layout/team-manager'
      path: '/team-manager'
      fullPath: '/team-manager'
      preLoaderRoute: typeof LayoutTeamManagerRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/stats': {
      id: '/_layout/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof LayoutStatsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/league-table': {
      id: '/_layout/league-table'
      path: '/league-table'
      fullPath: '/league-table'
      preLoaderRoute: typeof LayoutLeagueTableRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fixtures': {
      id: '/_layout/fixtures'
      path: '/fixtures'
      fullPath: '/fixtures'
      preLoaderRoute: typeof LayoutFixturesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin-dashboard': {
      id: '/_layout/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof LayoutAdminDashboardRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutAdminDashboardRoute: typeof LayoutAdminDashboardRoute
  LayoutFixturesRoute: typeof LayoutFixturesRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutLeagueTableRoute: typeof LayoutLeagueTableRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutStatsRoute: typeof LayoutStatsRoute
  LayoutTeamManagerRoute: typeof LayoutTeamManagerRoute
  LayoutTeamsRoute: typeof LayoutTeamsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutAdminDashboardRoute: LayoutAdminDashboardRoute,
  LayoutFixturesRoute: LayoutFixturesRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutLeagueTableRoute: LayoutLeagueTableRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutStatsRoute: LayoutStatsRoute,
  LayoutTeamManagerRoute: LayoutTeamManagerRoute,
  LayoutTeamsRoute: LayoutTeamsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
